// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACJfaqKmGHrKw9rPQtRkVfA6gNVM4uxgs',
    appId: '1:525520101020:web:c05d05a1acff4d18451759',
    messagingSenderId: '525520101020',
    projectId: 'carato-shopping-app',
    authDomain: 'carato-shopping-app.firebaseapp.com',
    databaseURL: 'https://carato-shopping-app-default-rtdb.firebaseio.com',
    storageBucket: 'carato-shopping-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRVJTby7UJYXyNiWy3aItnZAZEr8BUIs',
    appId: '1:525520101020:android:8bc9c7a43138b7f1451759',
    messagingSenderId: '525520101020',
    projectId: 'carato-shopping-app',
    databaseURL: 'https://carato-shopping-app-default-rtdb.firebaseio.com',
    storageBucket: 'carato-shopping-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfYNxk5OG-g_1fH7KYUwu2YvB85Dx4i4o',
    appId: '1:525520101020:ios:d7fbe8f1784a81b8451759',
    messagingSenderId: '525520101020',
    projectId: 'carato-shopping-app',
    databaseURL: 'https://carato-shopping-app-default-rtdb.firebaseio.com',
    storageBucket: 'carato-shopping-app.appspot.com',
    iosClientId: '525520101020-aa65i08keaubsj36hl1a198u6piki6sc.apps.googleusercontent.com',
    iosBundleId: 'com.solodev.shoppingApp',
  );
}
